#!/bin/bash

#                      _ _
#                     (_) |
#  _ __ _____   ___ __ _| |_ ____           github:     https://github.com/mvritz
# | '_ ` _ \ \ / / '__| | __|_  /           twitter:    https://twitter.com/meshtonight
# | | | | | \ V /| |  | | |_ / /            website:    https://moriware.com
# |_| |_| |_|\_/ |_|  |_|\__/___|
#

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"
source "$HOME/.config/sketchybar/environment.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
POPUP_CLICK_SCRIPT="sketchybar --set $NAME popup.drawing=toggle"
ACTIVE_SPACE=$(yabai -m query --spaces --space | jq '.index')

bar=(
  height=30
  margin=0
  corner_radius=10
  position=top
  color="$TRANSPARENT"
  border_color="$BORDER"
  y_offset=10
  sticky=off
)

sketchybar --bar "${bar[@]!}"

defaults=(
  updates=when_shown
  icon.drawing=on
  icon.font="SF Pro:Regular:14.0"
  icon.color="$WHITE"
  label.font="SF Pro:Regular:14.0"
  label.drawing=on
  label.color="$WHITE"
  popup.background.color="$BLUE"
  popup.background.corner_radius=10
  popup.background.border_width=2
  popup.background.border_color="$BORDER"
  popup.blur_radius=50
)

sketchybar --default "${defaults[@]!}"

time=(
  update_freq=1
  script="$PLUGIN_DIR/time.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label.font="SF Pro:Bold:14.0"
  label.padding_left=21
  label.padding_right=16
  background.corner_radius=10
  background.color="$TEMPUS"
  background.height=19
  background.padding_left=-10
  background.padding_right=3
  background.border_color="$BORDER"
)

sketchybar --add item time right \
  --set time "${time[@]!}" \
  --subscribe time system_woke

date=(
  update_freq=30
  script="$PLUGIN_DIR/date.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label.padding_left=16
  background.color="$TEMPUS"
  background.height=19
  background.corner_radius=10
)

sketchybar --add item date right \
  --set date "${date[@]!}" \
  --subscribe date system_woke

wifi=(
  script="$PLUGIN_DIR/wifi.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label.padding_right=16
  update_freq=60
)

rm -f /tmp/sketchybar_wifi
sketchybar --add item wifi right \
  --set wifi "${wifi[@]!}" \
  --subscribe wifi system_woke

battery=(
  script="$PLUGIN_DIR/battery.sh"
  update_freq=120
  updates=on
  click_script="$POPUP_CLICK_SCRIPT"
  label.padding_left=16
)

sketchybar --add item battery right \
  --set battery "${battery[@]!}" \
  --subscribe battery power_source_change system_woke

volume=(
  script="$PLUGIN_DIR/volume.sh"
  updates=on
  label.drawing=off
  icon.drawing=off
  slider.highlight_color="$PURPLE"
  slider.background.height=1
  slider.background.corner_radius=3
  slider.background.color="$GREY"
  slider.knob="$DOT"
  slider.knob.drawing=off
  slider.padding_left=15
  slider.padding_right=15
  label.padding_right=10
  label.padding_left=10
  background.color="$STATUS"
  background.height=10
  background.corner_radius=10
  background.border_width=1
  background.border_color="$BORDER"
  background.padding_right=7
)

sketchybar --add slider volume right \
  --set volume "${volume[@]!}" \
  --subscribe volume volume_change mouse.clicked mouse.entered mouse.exited

volume_icon=(
  script="$PLUGIN_DIR/volume_icon.sh"
  click_script="$PLUGIN_DIR/volume_click.sh"
  label.padding_right=8
  label.padding_left=21
)

sketchybar --add item volume_icon right \
  --set volume_icon "${volume_icon[@]!}"

ram=(
  icon="$RAM"
  icon.padding_left=16
  script="$PLUGIN_DIR/ram.sh"
  label.padding_right=16
  label.padding_left=10
  update_freq=60
  background.corner_radius=10
  background.color="$MIDNIGHT"
  background.height=25
  background.corner_radius=10
  background.padding_right=10 
  background.padding_left=-6
  background.border_color="$BORDER"
  background.border_width=2
  icon.padding_left=16
)

sketchybar --add item ram right \
  --set ram "${ram[@]!}"

cpu=(
  icon="$CPU"
  icon.padding_left=16
  script="$PLUGIN_DIR/cpu.sh" 
  label.padding_right=16
  label.padding_left=10
  update_freq=60
  background.corner_radius=10
  background.color="$MIDNIGHT"
  background.height=25
  background.corner_radius=10
  background.padding_right=10 
  background.padding_left=-6
  background.border_color="$BORDER"
  background.border_width=2
  icon.padding_left=16
)

sketchybar --add item cpu right \
  --set cpu "${cpu[@]!}"

apple=(
  script="$PLUGIN_DIR/apple.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label="$APPLE"
  label.padding_right=16
  label.padding_left=16
  background.color="$TEMPUS"
  background.height=19
  background.corner_radius=10
  background.padding_left=3
  background.padding_right=3
)

sketchybar --add item apple left \
  --set apple "${apple[@]!}"

space=(
  script="$PLUGIN_DIR/spaces.sh"
  label.drawing=off
  icon.padding_left=16
  icon.padding_right=16
  update_freq=1
)

space_bg=(
  background.color="$SPACEBG"
  background.height=19
  background.corner_radius=50
)

declare -a spacesArray=()
for i in "${!SPACE_GHOSTS[@]}"; do
  sid=$(($i + 1))

  if [[ $sid -eq $ACTIVE_SPACE ]]; then
    CURRENT_ICON=$PACMAN
  else
    CURRENT_ICON=${SPACE_GHOSTS["$i"]}
  fi

  spacesArray+=("space.$sid")

  sketchybar --add space space.$sid left \
    --set space.$sid associated_space=$sid \
    icon="$CURRENT_ICON" \
    click_script="yabai -m space --focus $sid" \
    "${space[@]}"

  if [[ $sid -eq $ACTIVE_SPACE ]]; then
    sketchybar --set space.$sid "${space_bg[@]}"
  fi
done

current_space=(
  icon.padding_left=16
  icon.padding_right=16
  background.color="$MIDNIGHT"
  background.height=25
  background.corner_radius=10
  background.border_color="$BORDER"
  background.border_width=2
  background.padding_left=10
  click_script="$PLUGIN_DIR/sort.sh"
)

sketchybar --add item current_space left \
  --set current_space "${current_space[@]!}"

brackets=(
  background.color="$STATUS"
  background.height=25
  background.corner_radius=10
  background.border_color="$BORDER"
  background.border_width=2
)

sketchybar --add bracket status time date wifi battery volume_icon right \
  --set status "${brackets[@]!}"

sketchybar --add bracket control apple "${spacesArray[@]!}" center \
  --set control "${brackets[@]!}"

sketchybar --update


echo "sketchybar configuration loaded!"