run_on_start = [
  "rift-cli subscribe cli --event windows_changed --command sh --args -c --args 'osascript -e \" tell application \\\"System Events\\\" to     if (get name of every process) contains \\\"AeroSpaceBar\\\" then         tell application \\\"AeroSpaceBar\\\" to «event ascrpsbr» \\\"updateOnFocusChanged\\\" \"'"
]