#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings based on .aerospace.toml
yabai -m config \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_origin_display default \
  window_placement second_child \
  window_shadow off \
  window_animation_duration 0.1 \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 1.0 \
  window_opacity on \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 8 \
  bottom_padding 16 \
  left_padding 16 \
  right_padding 16 \
  window_gap 16 \
  layout bsp \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# Workspace assignment from .aerospace.toml
yabai -m space 4 --display 1

# Rules from .aerospace.toml

# Move apps to workspaces
yabai -m rule --add app="^Safari$" space=1
yabai -m rule --add app="^Warp$" space=2
yabai -m rule --add app="^ghostty$" space=2
yabai -m rule --add app="^Cursor$" space=2
yabai -m rule --add app="^IntelliJ IDEA CE$" space=2
yabai -m rule --add app="^Xcode$" space=3
yabai -m rule --add app="^Mail$" space=4
yabai -m rule --add app="^Messages$" space=4
yabai -m rule --add app="^Beeper$" space=4

# Floating windows
yabai -m rule --add app="[Cc]ontacts" manage=off
yabai -m rule --add title="Phone" manage=off
yabai -m rule --add app="FaceTime" manage=off
yabai -m rule --add app="QuickTime Player" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Ollama" manage=off
yabai -m rule --add app="Calendar" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="[Gg][Pp][Tt]" manage=off
yabai -m rule --add app="Preview" manage=off
yabai -m rule --add app="Perplexity" manage=off
yabai -m rule --add app="App Store" manage=off

# Borders from .aerospace.toml
borders active_color=0x00000000 inactive_color=0x00000000 width=5.0 style=round hidpi=on blacklist="iPhone Mirroring" &

echo "yabai configuration loaded.."