# If you want to explore what each section of the configuration does in detail,
# visit: https://machlit.github.io/cutler

[set.menuextra.clock] # The preference is put without the com.apple. prefix (here it is com.apple.menuextra.clock)
FlashDateSeparators = false
Show24Hour = true
ShowAMPM = false
ShowDate = 0
ShowDayOfWeek = true
ShowSeconds = false

[set.finder]
AppleShowAllFiles = true
CreateDesktop = true                   # show all icons on the desktop, including external drives, connected servers, and removable media.
FXDefaultSearchScope = "SCcf"          # "SCcf" = Search the current folder, "SCev" = Search the entire Mac, "SCsp" = Search the previous search scope.
FXEnableExtensionChangeWarning = false
FXPreferredViewStyle = "Nlsv"
FXRemoveOldTrashItems = true
FinderSpawnTab = false
ShowExternalHardDrivesOnDesktop = true
ShowHardDrivesOnDesktop = false
ShowMountedServersOnDesktop = true
ShowPathbar = true
ShowRemovableMediaOnDesktop = true
ShowStatusBar = true
_FXSortFoldersFirst = true

[set.AppleMultitouchTrackpad]
FirstClickThreshold = 1
TrackpadThreeFingerDrag = false

[set.dock]
autohide = true
autohide-delay = 0
autohide-time-modifier = 0.5
expose-group-apps = true
magnification = false
mineffect = "genie"
mru-spaces = false           # keep the Spaces arrangement
orientation = "bottom"
show-recents = false
static-only = false
tilesize = 48

[set.HIToolbox]
AppleFnUsageType = 1 # wwitches between keyboard layouts for writing in other languages (known as input sources).

[set.spaces]
spans-displays = false # displays have separate Spaces

[set.screencapture]
location = "~/Downloads"
show-thumbnail = true
target = "file"
type = "png"

[set.NSGlobalDomain] # For global domains, use the NSGlobalDomain key.
AppleKeyboardUIMode = 0                      # 0 = disabled, 2 = enabled
AppleShowAllExtensions = true
NSAutomaticInlinePredictionEnabled = true
NSAutomaticPeriodSubstitutionEnabled = false
NSAutomaticSpellingCorrectionEnabled = true
NSDocumentSaveNewDocumentsToCloud = true
"com.apple.keyboard.fnState" = true
"com.apple.mouse.scaling" = 3

# cutler can also help you run shell commands every now and then.
# Store them inside their own [commands] table instance and run them by name using the command:
#
# `cutler exec <cmd_name>`

[vars]
hostname = "rdrkr-mbp-m1"

[command.hostname]
run = """
scutil --set ComputerName "Ronen's MacBook Pro M1 Pro"
scutil --set HostName $hostname
scutil --set LocalHostName $hostname
"""
ensure_first = true # ensure_first = true; Runs before all other commands.
sudo = true # sudo = true; When you want your command to run with sudo privileges.
# Please note that this is just a minor convenience feature;
# regular sudo inside your actual command still works.
