# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](level_1)\
$os\
$username\
[](bg:level_2 fg:level_1)\
$directory\
[](fg:level_2 bg:level_3)\
$git_branch\
$git_status\
[](fg:level_3 bg:level_4)\
$buf\
$c\
$cpp\
$dotnet\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$php\
$python\
$rust\
$scala\
$swift\
[](fg:level_4 bg:level_5)\
$aws\
$azure\
$docker_context\
[](fg:level_5 bg:level_6)\
$time\
[](fg:level_6)\
$fill\
[](fg:level_7)\
$battery\
[](fg:level_7)   \
$line_break$character\
"""

right_format = """
"""

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "gruvbox_dark"

# Palette definitions
[palettes.catppuccin_latte]
level_1 = "#d20f39" # red
level_2 = "#fe640b" # peach
level_3 = "#df8e1d" # yellow
level_4 = "#40a02b" # green
level_5 = "#04a5e5" # sky
level_6 = "#1e66f5" # blue
level_7 = "#7287fd" # lavender

[palettes.catppuccin_frappe]
level_1 = "#e78284" # red
level_2 = "#ef9f76" # peach
level_3 = "#e5c890" # yellow
level_4 = "#a6d189" # green
level_5 = "#99d1db" # sky
level_6 = "#8caaee" # blue
level_7 = "#7287fd" # lavender

[palettes.catppuccin_macchiato]
level_1 = "#ed8796" # red
level_2 = "#f5a97f" # peach
level_3 = "#eed49f" # yellow
level_4 = "#a6da95" # green
level_5 = "#91d7e3" # sky
level_6 = "#8aadf4" # bluecd
level_7 = "#7287fd" # lavender

[palettes.catppuccin_mocha]
level_1 = "#f38ba8" # red
level_2 = "#fab387" # peach
level_3 = "#f9e2af" # yellow
level_4 = "#a6e3a1" # green
level_5 = "#89dceb" # sky
level_6 = "#89b4fa" # blue
level_7 = "#7287fd" # lavender

[palettes.m365princess]
level_1 = "#9A348E" # plum
level_2 = "#DA627D" # blush
level_3 = "#FCA17D" # salmon
level_4 = "#86BBD8" # sky
level_5 = "#047E84" # teal
level_6 = "#33658A" # teal_blue
level_7 = "#7287fd" # lavender

[palettes.gruvbox_dark]
level_1 = '#cc241d' # red
level_2 = '#d65d0e' # orange
level_3 = '#d79921' # yellow
level_4 = '#98971a' # green
level_5 = '#689d6a' # aqua
level_6 = '#458588' # blue
level_7 = '#b16286' # purple

[line_break]
disabled = false

[fill]
disabled = false
symbol = ' '

#### Section 1 ####
# Disable the blank line at the start of the prompt
# add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:level_1 bold"
style_root = "bg:level_1 bold"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false
style = "bg:level_1 bold"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

#### Section 2 ####
[directory]
style = "bg:level_2 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Development" = "󰲋"

#### Section 3 ####
[buf]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[c]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[cpp]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[dotnet]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[elixir]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[elm]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[golang]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol]($style)'

[gradle]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[kotlin]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[haskell]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[java]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[julia]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[nodejs]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[nim]
symbol = "󰆥 "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[rust]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[scala]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

[swift]
symbol = " "
style = "bg:level_4 bold"
format = '[ $symbol($version )]($style)'

#### Section 4 ####
[git_branch]
symbol = ""
style = "bg:level_3 bold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:level_3 bold"
format = '[$all_status$ahead_behind ]($style)'

[docker_context]
symbol = " "
style = "bg:level_5 bold"
format = '[ $symbol $context ]($style)'

#### Section 5 ####
[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:level_6 bold"
format = '[  $time ]($style)'

#### Section 6 (Right) ####
[battery]
disabled = false
format = '[$symbol$percentage]($style)'

[[battery.display]]
threshold = 100
style = "bg:level_7 bold"

[[battery.display]]
threshold = 20
style = 'bg:level_7 bold'

[[battery.display]]
threshold = 10
style = 'bg:level_7 bold'

#### Prompt Section ####
[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
